from typing import Any, Mapping, Optional, Sequence, Union

DEFAULT_CLASSPATH: str

def start_jvm(classpath: Optional[Union[Sequence[str], str]] = ..., *args: Any, **kwargs: Any) -> None: ...
def shutdown_jvm() -> None: ...
def is_jvm_started() -> bool: ...

class JavaObjectWrapper:
    java_object: Any
    def __getattr__(self, name: str) -> Any: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class ConversionProperties(JavaObjectWrapper):
    def __init__(self) -> None: ...

class IFCtoLBDConverter(JavaObjectWrapper):
    def __init__(self, base_uri: str, level: int) -> None: ...
    def convert(self, ifc_file: str, properties: Optional[ConversionProperties] = ...) -> Any: ...
    def setProperty_replace_map(self, replacements: Union[Mapping[str, str], str]) -> Any: ...

class QueryFactory:
    @staticmethod
    def create(query_string: str) -> Any: ...

class QueryExecutionFactory:
    @staticmethod
    def create(query: Any, model: Any) -> Any: ...

class JavaHashMap(JavaObjectWrapper):
    def __init__(self, values: Optional[Mapping[Any, Any]] = ...) -> None: ...
    def put(self, key: Any, value: Any) -> Any: ...
